export const LLM_PROVIDER = 'LLM_PROVIDER';
export const CANDIDATE_PIPELINE_PROVIDER = 'CANDIDATE_PIPELINE_PROVIDER';
export const AI_LOGGER = 'AI_LOGGER';
export const TOPIC_EXTRACTOR_PROVIDER = 'TOPIC_EXTRACTOR_PIPELINE';